// <auto-generated />
using Jose_vargas_Apl1_p1.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Jose_vargas_Apl1_p1.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20220207232958_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("Jose_vargas_Apl1_p1.Entidades.Productos", b =>
                {
                    b.Property<int>("Productoid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Costo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Existencia")
                        .HasColumnType("TEXT");

                    b.Property<float>("ValorInventario")
                        .HasColumnType("REAL");

                    b.HasKey("Productoid");

                    b.ToTable("productos");
                });
#pragma warning restore 612, 618
        }
    }
}
